### ISSUE TITLE
Velop node stuck dim blue led after trying to flash openwrt image 

### ISSUE THREAD

**Issue by brucemiranda** [ishi0/Community-Fibre-WHW03CFv2#4]
I tried this procedure on 2 nodes. The first one went fine. The next one wouldn't complete the firmware upgrade to the install OpenWrt. Now the node won't even start up. When powered up I simply get a dim solid blue light. The reset button won't do anything. There is no WiFi or ethernet available from this node. How do I recover from a failed upgrade attempt?

**Comment by ishi0** [comment]
> I tried this procedure on 2 nodes. The first one went fine. The next one wouldn't complete the firmware upgrade to the install OpenWrt. Now the node won't even start up. When powered up I simply get a dim solid blue light. The reset button won't do anything. There is no WiFi or ethernet available from this node. How do I recover from a failed upgrade attempt? 

Hold reset for 20 seconds then power cycle while holding the reset button. It should boot into a backup partition of the LinkSys firmware and then you can attempt to do it again. Any problems message me.

**Comment by brucemiranda** [comment]
This turned out to be something very strange and probably embarrassing too. But I learnt something new as a result. When you load OpenWRT, the reset button is rendered useless. So no amount of pressing does anything. I even tried the 30 30 30 reset method. And nothing.
Then what I found out was OpenWRT configures Ethernet Port 1 as WAN and Ethernet Port 2 as LAN. Using a fixed IP address of 192.168.1.100 with a gateway of 192.168.1.1 on my PC Ethernet adapter, and moving the cable to Ethernet Port 2 allowed me to confirm that OpenWRT had indeed loaded successfully except I got no confirmation message via the UI. Then it was just the case of using the remaining steps. Previously my Ethernet  cable was connected to Port 1 and hence all the issues.
I learnt about this fact here
https://openwrt.org/toh/linksys/whw03_v2

**Comment by brucemiranda** [comment]
@ishi0 how is your version of the OpenWRT firmware different from the snapshot release? The file size is different, hence my question?

**Comment by ishi0** [comment]
> @ishi0 how is your version of the OpenWRT firmware different from the snapshot release? The file size is different, hence my question?

Hi, this firmware has a NAND patch applied to it. That's why this firmware works for the cfv2 routers. Older versions of the whw03v2 shipped with a different NAND chip. If I find the documentation I used I'll link it.

**Comment by brucemiranda** [comment]
Yes please because I am now completely fed up with the Velop system playing up and now plan to load OpenWRT on all of them and build my own mesh. 
For whatever reason while my Velop is set to Bridged mode the main WiFi isn't providing me an Internet connection even though I get a WiFi connection. Guest wifi provides an Internet connection.

**Comment by brucemiranda** [comment]
Closing this issue. This worked well except that you probably need to add to the instructions to use Ethernet Port 2 when working on it. Especially when the OpenWRT has been flashed on it because OpenWRT makes port 1 WAN only by default whereas the OEM stock firmware allows you to use both as LAN and Ethernet Port 1 as WAN. So if you start with the OEM firmware using Ethernet Port 1, then you wonder why you can't access the Velop Node once OpenWRT boots up.
